// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DriveUIClient is the client API for DriveUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriveUIClient interface {
	// ListEngineSpecs returns a list of Drive Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (DriveUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type driveUIClient struct {
	cc grpc.ClientConnInterface
}

func NewDriveUIClient(cc grpc.ClientConnInterface) DriveUIClient {
	return &driveUIClient{cc}
}

func (c *driveUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (DriveUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &DriveUI_ServiceDesc.Streams[0], "/v1.DriveUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &driveUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DriveUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type driveUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *driveUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *driveUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.DriveUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriveUIServer is the server API for DriveUI service.
// All implementations must embed UnimplementedDriveUIServer
// for forward compatibility
type DriveUIServer interface {
	// ListEngineSpecs returns a list of Drive Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, DriveUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedDriveUIServer()
}

// UnimplementedDriveUIServer must be embedded to have forward compatible implementations.
type UnimplementedDriveUIServer struct {
}

func (UnimplementedDriveUIServer) ListEngineSpecs(*ListEngineSpecsRequest, DriveUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedDriveUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedDriveUIServer) mustEmbedUnimplementedDriveUIServer() {}

// UnsafeDriveUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriveUIServer will
// result in compilation errors.
type UnsafeDriveUIServer interface {
	mustEmbedUnimplementedDriveUIServer()
}

func RegisterDriveUIServer(s grpc.ServiceRegistrar, srv DriveUIServer) {
	s.RegisterService(&DriveUI_ServiceDesc, srv)
}

func _DriveUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DriveUIServer).ListEngineSpecs(m, &driveUIListEngineSpecsServer{stream})
}

type DriveUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type driveUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *driveUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DriveUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DriveUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DriveUI_ServiceDesc is the grpc.ServiceDesc for DriveUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriveUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.DriveUI",
	HandlerType: (*DriveUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _DriveUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _DriveUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "drive-ui.proto",
}
